### ISSUE TITLE
Refresh rate detection doesn't work when using multiple screens with different refresh rate

### ISSUE THREAD

**Issue by SludgePhD** [aevyrie/bevy_framepace#44] opened 2023-07-22 16:01 UTC
The logic here only reruns when the plugin settings or `WinitWindows` change, but I don't think that will happen just by dragging a window to another screen:

https://github.com/aevyrie/bevy_framepace/blob/4ae0c483d4e813e4f41af02d4a03ac3b5319246e/src/lib.rs#L193

This then causes bevy_framepace to always use the initial screen's refresh rate, even when the window is moved over to another screen with a different refresh rate later, effectively rendering the plugin ineffective on that screen.

If calling `detect_frametime` every frame is too much work, perhaps the library could be made to work without having an accurate refresh rate value, by measuring the time bevy spends waiting for VSync? In my own experiments, I've managed to measure this by timing the executing time of the `prepare_windows` system.

**Comment by aevyrie** [comment] 2023-10-23 22:09
The reason for the check is that I found this was taking a significant amount of time, perhaps because a syscall or something is happening. I took another look at this and confirmed the function to get the best video mode was taking upwards of 6ms. Not sure if this was available when I first wrote this, but it now appears you can just use `MonitorHandle::refresh_rate_millihertz()`, which only takes a few microseconds. I'll switch this over on main.

**Comment by aevyrie** [comment] 2023-10-24 04:51
Fixed by https://github.com/aevyrie/bevy_framepace/commit/b29420d50acf854a32a39cda9a49c53d92b0fc18

**Closed by aevyrie** 2023-10-24 04:51 UTC
