### ISSUE TITLE
demo example is failing 

### ISSUE THREAD

**Issue by Dot32IsCool** [aevyrie/bevy_framepace#5] opened 2022-03-21 09:34 UTC
![Screen Shot 2022-03-21 at 17 22 12](https://user-images.githubusercontent.com/61964090/159234968-5df2272e-38d2-49ab-86ef-88066d62b42e.png)

Incase it matters, i'm on an m1 mac

`INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }`

**Comment by aevyrie** [comment] 2022-03-31 09:30
This should be fixed by 38d00a591733d82a220a4c9f8b67f7bdde0b05ff

The error you're seeing is caused by changes in bevy/main.

**Closed by aevyrie** 2022-03-31 09:30 UTC

**Comment by Dot32IsCool** [comment] 2022-04-01 09:46
sweet!
